linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errname
    - errorlint
    - gci
    - goconst
    - gocritic

issues:
  exclude-rules:
    - path: 'backend/backend.go'
      linters:
        - errorlint
