global:
  scrape_interval:     1s
  evaluation_interval: 1s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: metrics
    static_configs:
      - targets: ['localhost:8081']